default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false
      - id: commit-msg
        name: conventional commit header
        entry: tools/commit_msg.py
        language: script
        stages: [commit-msg]
